apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: node-restify-validation
  description: ""
  annotations: []
spec:
  type: library
  lifecycle: production
  domain: tech-foundation
  system: architecture
  owner: architecture
relations: []
